<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKICeyOH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKICeyOH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKICeyOH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKICeyOH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKICeyOH\App_KernelProdContainer([
    'container.build_hash' => 'KICeyOH',
    'container.build_id' => '63efe566',
    'container.build_time' => 1723828395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKICeyOH');
